const FIND='/find';
const GetById='/get_by_id';
const updateUser='/update_user';
const AddReview='/Review/add';
const getReview='/show_street_reviews';
const getGarageReview='/show_garage_reviews';
const getGarage='/Garage/get';
const getGarageById='/Garage/get?id=';
const getCamera='/Camera/get';
const ShowStreetReview ="/show_street_reviews";
const GetUserBookMark="/get_user_bookmark";
const AddBookMark="/Bookmark/add";
const AddRecent = "/Recent/add";
const getRecent = "/Recent/get";
const requestSnap = "/mocking_camera";
const LOGIN='/log_in';
const SIGNUP='/sign_up';
const getSnapsById='/Snaps/get?id=';
const getGarageCameraById='/GarageCamera/get?id=';
const getGarageSnapsById='/GarageSnaps/get?id=';